import { setupFixture } from "@ws-tools/scripts/jest/setupFixture";
import type { ParsedLock } from "../../lockfile/types";
import { parseLockFile } from "../../lockfile/parseLockFile";
import { queryLockFile } from "../../lockfile/queryLockFile";

const getPackageVersion = (packageName: string, parsedLockFile: ParsedLock) => {
  const packageSpec = Object.keys(parsedLockFile.object).find((spec) => spec.startsWith(`${packageName}@`));
  expect(packageSpec).toBeTruthy();
  return parsedLockFile.object[packageSpec!].version;
};

// TODO: The lock file logic is extremely broken, and this was likely not testing anything
// meaningful to begin with...
xdescribe("queryLockFile", () => {
  describe("NPM", () => {
    it("retrieves a dependency from a lock generated by npm", async () => {
      const packageName = "@types/node";
      const packageRoot = setupFixture("monorepo-basic-npm");
      const parsedLockFile = await parseLockFile(packageRoot);
      const packageVersion = getPackageVersion(packageName, parsedLockFile)!;
      expect(packageVersion).toBeTruthy();

      const result = queryLockFile(packageName, packageVersion, parsedLockFile);
      expect(result).toBeTruthy();
      expect(result.version).toBe(packageVersion);
    });
  });

  describe.each(["1", "berry"] as const)("yarn %s", (yarnVersion) => {
    it("retrieves a dependency from a lock generated by yarn", async () => {
      const packageName = "@types/node";
      const packageRoot = setupFixture(`extra-yarn-${yarnVersion}`);
      const parsedLockFile = await parseLockFile(packageRoot);
      const packageVersion = getPackageVersion(packageName, parsedLockFile)!;
      expect(packageVersion).toBeTruthy();

      // NOTE: Yarn’s locks include ranges.
      const result = queryLockFile(packageName, `^${packageVersion}`, parsedLockFile);
      expect(result).toBeTruthy();
      expect(result.version).toBe(packageVersion);
    });
  });

  describe("PNPM", () => {
    it("retrieves a dependency from a lock generated by pnpm", async () => {
      const packageName = "@changesets/cli";
      const packageRoot = setupFixture("monorepo-basic-pnpm");
      const parsedLockFile = await parseLockFile(packageRoot);
      const packageVersion = getPackageVersion(packageName, parsedLockFile)!;
      expect(packageVersion).toBeTruthy();

      const result = queryLockFile(packageName, packageVersion, parsedLockFile);
      expect(result).toBeTruthy();
      expect(result.version).toBe(packageVersion);
    });
  });
});
