import { setupFixture } from "../helpers/setupFixture";
import { parseLockFile, queryLockFile } from "..";

const packageName = "@microsoft/task-scheduler";
const packageVersion = "2.7.1";

describe("queryLockFile()", () => {
  // NPM
  it("retrieves a dependency from a lock generated by npm", async () => {
    const packageRoot = await setupFixture("monorepo-npm");
    const parsedLockFile = await parseLockFile(packageRoot);
    const result = queryLockFile(packageName, packageVersion, parsedLockFile);

    expect(result).toBeDefined();
    expect(result.version).toBe(packageVersion);
  });

  // Yarn
  it("retrieves a dependency from a lock generated by yarn", async () => {
    const packageRoot = await setupFixture("basic-yarn");
    const parsedLockFile = await parseLockFile(packageRoot);
    // NOTE: Yarn’s locks include ranges.
    const result = queryLockFile(packageName, `^${packageVersion}`, parsedLockFile);

    expect(result).toBeDefined();
    expect(result.version).toBe(packageVersion);
  });

  // PNPM
  it("retrieves a dependency from a lock generated by pnpm", async () => {
    const packageRoot = await setupFixture("monorepo-pnpm");
    const parsedLockFile = await parseLockFile(packageRoot);
    const result = queryLockFile(packageName, packageVersion, parsedLockFile);
  
    expect(result).toBeDefined();
    expect(result.version).toBe(packageVersion);
  });
});
